import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";
import NavBottomBar, { routesConfig } from "../components/NavBottomBar";
import { useState } from "react";
import { useRouter } from "next/navigation";

const Home: NextPage = () => {
  const router = useRouter();
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const [activePage, setActivePage] = useState(routesConfig.home);

  const changePage = (route: string) => {
    setActivePage(route);
    router.push(route);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main data-theme="dracula">
        <Link href={activePage} />
        <NavBottomBar activePage={activePage} setActivePage={changePage} />
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="btn"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
